/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banxclient.views.deigns.panels;

/**
 *
 * @author Software
 */
public class AbstractClientOperationsPanel extends javax.swing.JPanel {

    /**
     * Creates new form AbstractClientOperationsPanel
     */
    public AbstractClientOperationsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        makeTransactionButton = new javax.swing.JButton();
        transactionFormPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        themeTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        payementTypeComboBox = new javax.swing.JComboBox<>();
        typeOperationComboBox = new javax.swing.JComboBox<>();
        typeOperationLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        makeTransactionButton.setBackground(new java.awt.Color(0, 0, 255));
        makeTransactionButton.setForeground(new java.awt.Color(255, 255, 255));
        makeTransactionButton.setLabel("Procéder");
        makeTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeTransactionButtonActionPerformed(evt);
            }
        });

        transactionFormPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Somme");

        amountTextField.setText("...");
        amountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Thème");

        themeTextField.setText("...");

        jLabel4.setText("Moyen de payement");

        payementTypeComboBox.setBackground(new java.awt.Color(255, 255, 255));
        payementTypeComboBox.setForeground(new java.awt.Color(0, 0, 0));
        payementTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espèce", "Chèque", "Carte bancaire" }));

        typeOperationComboBox.setBackground(new java.awt.Color(255, 255, 255));
        typeOperationComboBox.setForeground(new java.awt.Color(0, 0, 0));
        typeOperationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dépot", "Retrait" }));

        typeOperationLabel.setForeground(new java.awt.Color(0, 0, 0));
        typeOperationLabel.setText("Type d'opération");

        javax.swing.GroupLayout transactionFormPanel1Layout = new javax.swing.GroupLayout(transactionFormPanel1);
        transactionFormPanel1.setLayout(transactionFormPanel1Layout);
        transactionFormPanel1Layout.setHorizontalGroup(
            transactionFormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionFormPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transactionFormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionFormPanel1Layout.createSequentialGroup()
                        .addGroup(transactionFormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountTextField)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(themeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(transactionFormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(payementTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionFormPanel1Layout.createSequentialGroup()
                        .addComponent(typeOperationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(typeOperationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        transactionFormPanel1Layout.setVerticalGroup(
            transactionFormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionFormPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(transactionFormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeOperationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeOperationLabel))
                .addGap(35, 35, 35)
                .addGroup(transactionFormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transactionFormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(payementTypeComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(amountTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(534, Short.MAX_VALUE)
                .addComponent(makeTransactionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(transactionFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addComponent(makeTransactionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(transactionFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(44, 44, 44)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void makeTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeTransactionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makeTransactionButtonActionPerformed

    private void amountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField amountTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    protected javax.swing.JButton makeTransactionButton;
    protected javax.swing.JComboBox<String> payementTypeComboBox;
    protected javax.swing.JTextField themeTextField;
    protected javax.swing.JPanel transactionFormPanel1;
    protected javax.swing.JComboBox<String> typeOperationComboBox;
    protected javax.swing.JLabel typeOperationLabel;
    // End of variables declaration//GEN-END:variables
}
