/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banxclient.views.deigns.panels;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Software
 */
public class AbstractClientSoldeChartPanel extends javax.swing.JPanel{

    /**
     * Creates new form ClientSoldChartPanelView
     */
    public AbstractClientSoldeChartPanel() {
        initComponents();
        JPanel p = new JPanel();
        p.setBackground(Color.red);
        p.setVisible(true);
        
        this.soldeChartPanel.add(p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshChartButton = new javax.swing.JButton();
        soldeChartPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(253, 253, 253));

        refreshChartButton.setBackground(new java.awt.Color(0, 0, 255));
        refreshChartButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshChartButton.setText("Rafraichir");
        refreshChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshChartButtonActionPerformed(evt);
            }
        });

        soldeChartPanel.setBackground(new java.awt.Color(255, 255, 255));
        soldeChartPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(refreshChartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(soldeChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(soldeChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshChartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshChartButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshChartButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton refreshChartButton;
    public javax.swing.JPanel soldeChartPanel;
    // End of variables declaration//GEN-END:variables
}
